name: Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
      - run: yarn install
      - run: yarn generate
      - uses: actions/upload-artifact@v4
        with:
          name: mirrors-frontend-build
          path: .output/public/
